---
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: add newly created host to temporary inventory
      add_host:
      args: "{{ lookup('template', 'add_host.j2') | from_yaml }}"

- hosts: new_vms
  gather_facts: true
  roles:
    - { role: app1, when 'app1' in app_list or app_list == 'all' }
    - { role: app2, when 'app2' in app_list or app_list == 'all' }
    - { role: app3, when 'app3' in app_list or app_list == 'all' }
