---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - debug: var=vm_details

    - name:  add newly created host to temporary inventory
      add_host: "{{ vm_details }}"

- hosts: new_vms
  gather_facts: no
  tasks:
    wait_for_connection:
