---
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - debug: var=vm_details

    - name: add newly created host to temporary inventory
      add_host:
          hostname: "{{ vm_details.hostname }}"
          ansible_port: "{{ vm_details.ansible_port }}"
          groups: "{{ vm_details.groups }}"
          app_list: "{{ vm_details.app_list }}"

- hosts: new_vms
  gather_facts: false
  tasks:
    - name: wait for VM to come back up
      wait_for_connection:
