---
- hosts: docker_host
  gather_facts: no
  tasks:
    - debug: msg="{{ ansible private key file: DEBUG ... {{ansible_ssh_private_key_file}} "

    - name: create Docker container simulates VM creation
      docker_container:
        state: started
        name: "ts{{ vm_details.ansible_port }}"
        image: linuxsimba/python-and-ssh
        ports:
          - "{{ vm_details.ansible_port }}"
        env:
          AUTHORIZED_KEYS="{{ ssh_pub_key }}"
