---
- hosts: docker_host
  gather_facts: no
  tasks:
    - name: create Docker container simulates VM creation
      docker_container:
        state: started
        name: "ts{{ vm_details.ansible_port }}"
        image: linuxsimba/python-and-ssh
        ports:
          - "{{ vm_details.ansible_port }}"
        env:
          AUTHORIZED_KEYS="{{ ssh_pub_key }}"
